name: ETL Workflow

on:
  schedule:
    - cron: '0 15 * * 1'  # Runs every Monday at 3 PM UTC

jobs:
  run_etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt


      - name: Run ETL process
        run: python main.py
