name: ETL Workflow

on:
  schedule:
    - cron: '0 15 * * 1'  # Runs every Monday at 3 PM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: List files in the working directory
        working-directory: ${{ github.workspace }}
        run: |
          pwd
          ls -R  # This helps verify the file structure and identify any missing files

      - name: Run ETL process and log output
        working-directory: ${{ github.workspace }}
        run: python main.py  # Run main.py which now generates etl_workflow.log

      - name: Upload ETL log file
        if: always()  # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: etl_workflow_log  # Name of the artifact
          path: etl_workflow.log  # Path to the log file
