name: ETL Workflow

on:
  schedule:
    - cron: '0 15 * * 1'  # Runs every Monday at 3 PM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  run_etl:
    runs-on: ubuntu-latest
    environment: AZURE_CONNECTION_STRING
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List all environment variables for debugging
        run: printenv | sort

      - name: Run ETL process
        env:
          AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
        run: python main.py
